export interface Quote {
  text: string;
  author: string;
}

function getDayOfYear(): number {
  const now = new Date();
  return Math.floor((now.getTime() - new Date(now.getFullYear(), 0, 0).getTime()) / 86400000);
}

export const MORNING_QUOTES: Quote[] = [
  { text: "Wir sind, was wir wiederholt tun. Exzellenz ist daher keine Handlung, sondern eine Gewohnheit.", author: "Aristoteles" },
  { text: "Disziplin ist die Brücke zwischen Ziel und Leistung.", author: "Jim Rohn" },
  { text: "Wer jeden Morgen gewinnt, gewinnt den Tag. Wer jeden Tag gewinnt, gewinnt sein Leben.", author: "Robin Sharma" },
  { text: "Tue zuerst das Notwendige, dann das Mögliche — und plötzlich schaffst du das Unmögliche.", author: "Franz von Assisi" },
  { text: "Der Schmerz der Disziplin ist leichter zu tragen als der Schmerz des Bedauerns.", author: "Bob Andrews" },
  { text: "Erfolg ist die Summe kleiner Anstrengungen, die täglich wiederholt werden.", author: "Robert Collier" },
  { text: "Ein Schritt nach dem anderen — auch eine Reise von tausend Meilen beginnt so.", author: "Laozi" },
  { text: "Jedes Meisterwerk beginnt mit dem ersten, unbeholfenen Strich.", author: "Unbekannt" },
  { text: "Disziplin bedeutet, das zu wählen, was du wirklich willst, über das, was du jetzt willst.", author: "Unbekannt" },
  { text: "Der einzige Weg, großartige Arbeit zu leisten, ist zu lieben, was du tust.", author: "Steve Jobs" },
  { text: "Die Fähigkeit, sich zu konzentrieren, ist das Fundament aller Leistung.", author: "Brian Tracy" },
  { text: "Es ist nicht genug, beschäftigt zu sein — die Frage ist: Womit bist du beschäftigt?", author: "Henry David Thoreau" },
  { text: "Wo deine Aufmerksamkeit hingeht, fließt deine Energie hin.", author: "Unbekannt" },
  { text: "Tue eine Sache. Tue sie gut. Tue sie jetzt.", author: "Unbekannt" },
  { text: "Kein Wind ist dem günstig, der keinen Hafen kennt.", author: "Michel de Montaigne" },
  { text: "Klarheit ist Kraft. Wer weiß, wohin er will, findet auch den Weg.", author: "Unbekannt" },
  { text: "Der Unterschied zwischen dem Gewöhnlichen und dem Außergewöhnlichen ist dieses kleine Extra.", author: "Jimmy Johnson" },
  { text: "Konzentration ist der Preis, den man für die Macht bezahlt.", author: "Napoleon Hill" },
  { text: "Eins nach dem anderen — und das erste ist Klarheit über das Ziel.", author: "Unbekannt" },
  { text: "Der Verstand ist scharf wie ein Messer: Er braucht Richtung, keine Geschwindigkeit.", author: "Unbekannt" },
  { text: "Wachstum und Komfort können nicht koexistieren.", author: "Ginni Rometty" },
  { text: "Werde jeden Tag ein bisschen besser als gestern.", author: "Unbekannt" },
  { text: "Scheitern ist kein Gegenteil von Erfolg — es ist sein Bestandteil.", author: "Arianna Huffington" },
  { text: "Jede Meisterschaft verlangt eine Phase des Lächerlichmachens.", author: "Unbekannt" },
  { text: "Die Komfortzone ist ein schöner Ort — aber dort wächst nichts.", author: "Unbekannt" },
  { text: "Fortschritt ist die Summe aus Mut, Geduld und konsequentem Tun.", author: "Unbekannt" },
  { text: "Lerne, als würdest du ewig leben. Lebe, als würdest du morgen sterben.", author: "Mahatma Gandhi" },
  { text: "Der Baum, der den stärksten Sturm überstanden hat, hat die tiefsten Wurzeln.", author: "Unbekannt" },
  { text: "Was dich nicht umbringt, macht dich stärker — wenn du es zulässt.", author: "Unbekannt" },
  { text: "Du musst bereit sein zu wachsen, wo du gepflanzt wurdest.", author: "Janet Erskine Stuart" },
  { text: "Erfolg ist kein Zufall. Er ist harte Arbeit, Ausdauer, Lernen, Studium und Aufopferung.", author: "Pelé" },
  { text: "Träume groß. Plane klug. Arbeite täglich.", author: "Unbekannt" },
  { text: "Der Unterschied zwischen einem Ziel und einem Traum ist ein Datum.", author: "Unbekannt" },
  { text: "Niemand, der sein Bestes gegeben hat, hat es jemals bereut.", author: "George Halas" },
  { text: "Mittelmäßigkeit ist eine Entscheidung — genauso wie Exzellenz.", author: "Unbekannt" },
  { text: "Du kannst deinen Charakter nicht verbergen — er kommt täglich ans Licht.", author: "Unbekannt" },
  { text: "Entscheide dich jeden Morgen neu: Wer willst du heute sein?", author: "Unbekannt" },
  { text: "Menschen, die niemals aufgeben, können nicht verlieren.", author: "Unbekannt" },
  { text: "Was du heute bist, ist das Ergebnis deiner Gedanken von gestern.", author: "Unbekannt" },
  { text: "Nur wer seine Vergangenheit kennt, kann seine Zukunft gestalten.", author: "Wilhelm von Humboldt" },
  { text: "Der Morgen ist weiser als der Abend.", author: "Russisches Sprichwort" },
  { text: "Jeder neue Tag ist eine neue Chance, das zu werden, was du sein könntest.", author: "Unbekannt" },
  { text: "Das Leben belohnt Handlungen, nicht Absichten.", author: "Unbekannt" },
  { text: "Wer immer tut, was er schon kann, bleibt immer das, was er schon ist.", author: "Henry Ford" },
  { text: "Ein Mensch ist erst dann wirklich frei, wenn er sich selbst beherrscht.", author: "Unbekannt" },
  { text: "Die meisten Menschen überschätzen ein Jahr und unterschätzen zehn Jahre.", author: "Bill Gates" },
  { text: "Wähle den schwierigen Weg heute, damit dein zukünftiges Ich stolz auf dich ist.", author: "Unbekannt" },
  { text: "Verändere deine Gedanken, und du veränderst deine Welt.", author: "Norman Vincent Peale" },
  { text: "Der beste Zeitpunkt, einen Baum zu pflanzen, war vor zwanzig Jahren. Der zweitbeste ist jetzt.", author: "Chinesisches Sprichwort" },
  { text: "Die größten Abenteuer liegen jenseits der Grenzen deiner Komfortzone.", author: "Unbekannt" },
];

export const EVENING_QUOTES: Quote[] = [
  { text: "Der Schlaf ist die beste Meditation.", author: "Dalai Lama" },
  { text: "Ein guter Tag verdient einen guten Abend.", author: "Unbekannt" },
  { text: "Ruhe ist nicht Trägheit — sie ist der Boden, aus dem morgen wächst.", author: "Unbekannt" },
  { text: "Was du heute gut gemacht hast, zählt. Lass es zur Ruhe kommen.", author: "Unbekannt" },
  { text: "Der Abend ist die Zeit, das Herz zu leeren, damit morgen wieder Platz ist.", author: "Unbekannt" },
  { text: "Wer gut schläft, regiert sein Leben.", author: "Unbekannt" },
  { text: "Das Loslassen am Abend ist ein Geschenk an dich selbst.", author: "Unbekannt" },
  { text: "Geh schlafen im Frieden, wache auf mit Absicht.", author: "Unbekannt" },
  { text: "Die Nacht hat ihre eigene Weisheit. Höre ihr zu.", author: "Unbekannt" },
  { text: "Jede Nacht ist ein kleines Sterben — und jeder Morgen eine kleine Auferstehung.", author: "Unbekannt" },
  { text: "Dankbarkeit verwandelt das, was wir haben, in genug.", author: "Unbekannt" },
  { text: "Ein dankbares Herz ist ein Magnet für Wunder.", author: "Unbekannt" },
  { text: "Am Ende des Tages zählt nicht, was du besessen hast — sondern was dich berührt hat.", author: "Unbekannt" },
  { text: "Finde jeden Abend drei Dinge, für die du dankbar bist. Dein Gehirn verändert sich.", author: "Unbekannt" },
  { text: "Wer nicht dankbar für das Kleine ist, verdient das Große nicht.", author: "Unbekannt" },
  { text: "Dankbarkeit ist kein Gefühl — sie ist eine Entscheidung.", author: "Unbekannt" },
  { text: "Das Schönste an einem schweren Tag ist, dass er endet.", author: "Unbekannt" },
  { text: "Wenn du nicht weißt, wofür du dankbar sein sollst — atme tief. Das reicht.", author: "Unbekannt" },
  { text: "Das Herz, das zählt, was es hat, wird reich.", author: "Unbekannt" },
  { text: "Jeder Abend trägt in sich ein Geschenk — du musst es nur erkennen.", author: "Unbekannt" },
  { text: "Das ungeprüfte Leben ist es nicht wert, gelebt zu werden.", author: "Sokrates" },
  { text: "Am Ende des Tages ist die einzige Frage: Habe ich heute mein Bestes gegeben?", author: "Unbekannt" },
  { text: "Wachstum beginnt am Ende des Tages, wenn du ehrlich mit dir bist.", author: "Unbekannt" },
  { text: "Ein Tag ohne Reflexion ist ein Tag ohne Lernen.", author: "Unbekannt" },
  { text: "Stille ist die Sprache Gottes — alles andere ist schlechte Übersetzung.", author: "Rumi" },
  { text: "Kein Mensch, der sich täglich beobachtet, bleibt derselbe.", author: "Unbekannt" },
  { text: "Was wäre gewesen, wenn du heute noch mehr du selbst gewesen wärst?", author: "Unbekannt" },
  { text: "Der Abend ist der Spiegel des Tages. Sieh ehrlich hinein.", author: "Unbekannt" },
  { text: "Jeder Tag, über den du nachgedacht hast, wurde gelebt — nicht nur verbraucht.", author: "Unbekannt" },
  { text: "Die stillen Momente am Abend sind die wertvollsten des Tages.", author: "Unbekannt" },
  { text: "Frieden ist nicht die Abwesenheit von Chaos — sondern deine Reaktion darauf.", author: "Unbekannt" },
  { text: "Vergib dir heute. Beginne morgen neu.", author: "Unbekannt" },
  { text: "Lass die Gedanken des Tages ziehen wie Wolken am Himmel.", author: "Unbekannt" },
  { text: "Du hast genug getan. Du bist genug.", author: "Unbekannt" },
  { text: "Die Nacht heilt vieles, was der Tag zerbrochen hat.", author: "Unbekannt" },
  { text: "Akzeptanz ist nicht Resignation — sie ist die Basis für echten Wandel.", author: "Unbekannt" },
  { text: "Nicht jeder Gedanke braucht eine Antwort. Lass ihn einfach sein.", author: "Unbekannt" },
  { text: "Frieden liegt nicht darin, alles kontrolliert zu haben — sondern loslassen zu können.", author: "Unbekannt" },
  { text: "Der ruhige See spiegelt die Sterne.", author: "Unbekannt" },
  { text: "Was sich nicht lösen lässt, braucht keine Lösung — nur Geduld.", author: "Unbekannt" },
  { text: "Jeder Tag ist ein abgeschlossenes Kunstwerk. Signiere es mit Würde.", author: "Unbekannt" },
  { text: "Das Beste, was du für morgen tun kannst, ist gut zu schlafen.", author: "Unbekannt" },
  { text: "Lebe so, dass du am Abend lächeln kannst.", author: "Unbekannt" },
  { text: "Heute war ein guter Kampf. Morgen kämpfst du wieder.", author: "Unbekannt" },
  { text: "Die Kraft eines Menschen zeigt sich nicht darin, wie er beginnt — sondern wie er abschließt.", author: "Unbekannt" },
  { text: "Wer jeden Abend abschließt, öffnet sich dem nächsten Morgen vollständig.", author: "Unbekannt" },
  { text: "Das Bewusstsein, gelebt zu haben, ist der beste Schlaftrunk.", author: "Unbekannt" },
  { text: "Schließ deine Augen mit einem Lächeln — der Rest kommt von selbst.", author: "Unbekannt" },
  { text: "Gute Nacht — ein kleines Wort für das größte Geschenk: einen neuen Tag morgen.", author: "Unbekannt" },
  { text: "Die Sterne leuchten nicht für uns — aber es hilft, es so zu glauben.", author: "Unbekannt" },
];

export const MORNING_AFFIRMATIONS: string[] = [
  "Ich bin fokussiert und bereit für diesen Tag.",
  "Ich bin stark genug für alles, was heute kommt.",
  "Ich bin dankbar für das Leben, das ich lebe.",
  "Ich bin die beste Version meiner selbst — täglich wachsend.",
  "Ich bin ein Mensch, der seine Versprechen hält.",
  "Ich bin ruhig, klar und entschlossen.",
  "Ich bin mutig genug, das Richtige zu tun.",
  "Ich bin ein Macher, kein Aufschieber.",
  "Ich bin im Einklang mit meinen tiefsten Werten.",
  "Ich bin gesund, energiegeladen und leistungsbereit.",
  "Ich bin der Architekt meines Lebens.",
  "Ich bin jemand, der jeden Tag besser wird.",
  "Ich bin geduldig mit mir und konsequent im Handeln.",
  "Ich bin bereit, Unbehagen zu akzeptieren und trotzdem zu handeln.",
  "Ich bin jemand, der Dankbarkeit täglich lebt.",
  "Ich bin verantwortlich für meine Gedanken, Worte und Taten.",
  "Ich bin in der Lage, jeden Rückschlag in einen Vorteil zu verwandeln.",
  "Ich bin ein Mensch mit Klarheit, Ziel und Richtung.",
  "Ich bin bereit, heute Großes zu beginnen.",
  "Ich bin jemand, dem andere vertrauen und auf den sie zählen können.",
  "Ich bin ein positiver Einfluss in meiner Welt.",
  "Ich bin entschlossen, keine Minute zu verschwenden.",
  "Ich bin mehr als meine Gewohnheiten — und ich forme sie täglich neu.",
  "Ich bin fähig, meinen Geist zu kontrollieren.",
  "Ich bin ein Mensch der Tat, nicht nur der Worte.",
  "Ich bin neugierig, offen und lernbereit.",
  "Ich bin im Besitz meiner vollen Aufmerksamkeit.",
  "Ich bin ein Gewinner — nicht weil ich immer gewinne, sondern weil ich nie aufgebe.",
  "Ich bin fähig, selbst schwierige Entscheidungen zu treffen.",
  "Ich bin jemand, der tief atmet, bevor er reagiert.",
  "Ich bin ein Mensch mit Integrität und Charakter.",
  "Ich bin bereit, heute Verantwortung zu übernehmen.",
  "Ich bin der Hauptdarsteller meines Lebens — nicht der Zuschauer.",
  "Ich bin stark in meiner Identität und klar in meiner Mission.",
  "Ich bin jemand, der das Beste in anderen sieht.",
  "Ich bin diszipliniert, weil ich es meinem zukünftigen Selbst schulde.",
  "Ich bin ein Mensch, der Hindernisse als Chancen sieht.",
  "Ich bin voller Energie und Absicht für diesen Tag.",
  "Ich bin jemand, der ehrlich mit sich selbst ist.",
  "Ich bin größer als meine Ängste.",
  "Ich bin jemand, der täglich Fortschritt über Perfektion wählt.",
  "Ich bin im Fluss meines Lebens und vertraue dem Prozess.",
  "Ich bin jemand, der schwierige Situationen mit Würde meistert.",
  "Ich bin ein Mensch, der seine Gedanken bewusst wählt.",
  "Ich bin bereit, heute meinen besten Tag zu haben.",
  "Ich bin ein Mensch mit starken Gewohnheiten und schwachen Ausreden.",
  "Ich bin wertvoll, unabhängig von meiner Produktivität.",
  "Ich bin in der Lage, heute etwas zu tun, das mein zukünftiges Ich danken wird.",
  "Ich bin jemand, der weiß, warum er aufsteht.",
  "Ich bin bereit. Der Tag gehört mir.",
];

export function getMorningQuote(): Quote {
  return MORNING_QUOTES[getDayOfYear() % MORNING_QUOTES.length];
}

export function getEveningQuote(): Quote {
  return EVENING_QUOTES[getDayOfYear() % EVENING_QUOTES.length];
}

export function getMorningAffirmation(): string {
  return MORNING_AFFIRMATIONS[(getDayOfYear() + 7) % MORNING_AFFIRMATIONS.length];
}
